### ISSUE TITLE
Cannot deploy project

### ISSUE THREAD

**Issue by elpatron68** [jedfonner/MattermostOnFire#1]
Hi, @jedfonner !

Thanks for this, I´d really like to try it out but I wasn´t able to deploy the project to Firebase. Do you have any idea what´s going wrong here?

I just edited `.firebasrc`, set my project name and tried to deploy with `firebase deploy`.
The `firebase login` was ok. My Node version is 8.9.3 on Windows.

```
=== Deploying to 'mattermostonfire-13513'...

i  deploying database, storage, firestore, functions, hosting
i  database: checking rules syntax...
+  database: rules syntax for database mattermostonfire-13513 is valid
i  storage: checking storage.rules for compilation errors...
+  storage: rules file storage.rules compiled successfully
i  firestore: checking firestore.rules for compilation errors...
+  firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  storage: uploading rules storage.rules...
i  firestore: uploading rules firestore.rules...
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'token' of undefined
    at Object.<anonymous> (C:\Users\xxx\AppData\Local\Temp\fbfn_9072E2sI87dyCPBP\utils.js:3:59)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xxx\AppData\Local\Temp\fbfn_9072E2sI87dyCPBP\index.js:3:15)
    at Module._compile (module.js:635:30)
```

Regards,
Markus

**Comment by jedfonner** [comment]
@elpatron68 Hi Markus - try running step 5 and 6 from the README to set the environment variables before deploying.  If that works, let me know and I will update the README.

**Comment by elpatron68** [comment]
Hi Jed, I am not sure if I have got it right, but as I understood this Firebase thing, I get my URL mentioned in step 5 after successfully deploying the project. As I cannot deploy, I cannot set the environment.

So what I did was:
- Git clone this project
- Opened a new project in Firebase, activated Firestore database
- `firebase login`
- Edit `.firebasrc` and change project name
- `firebase deploy --only ` or `firebase deploy` fail with the upper error.

I´m quite sure, I missed something, my Firebase knowledge reduces to a demo project I made as Google acquired them years ago.

**Comment by jedfonner** [comment]
Hi Markus - I apologize for the rough start. I went through the process of deploying to a new Firebase project and discovered that my initial guidelines left much to be desired.  I've updated the instructions now to be more clear - see https://github.com/jedfonner/MattermostOnFire#set-up

One thing to note: I removed the `.firebaserc` file from version control, because that is supposed to be specific to your individual project and I goofed when I initially included it.  Since you cloned an older version of the repo, you'll still have my version of `.firebaserc`.  Please remove that after you pull again before going through the deployment steps.

If you continue to have problems or if I missed anything, please let me know and I'll do my best to help.

**Comment by elpatron68** [comment]
Hi Jed,

thanks so much, gone through the installation in 15 minutes without any issues!

Bye, Markus
